### ISSUE TITLE
Error creating new neighbourhood

### ISSUE THREAD

**Issue by P-J-Brown** [martijnbentum/WaterSystem#2]
Hi Martijn,

I was trying to add the neighbourhoods for Damascus but when I click the 'save' button after entering the information and choosing the .json file I get a page saying "Server Error (500)"

This is not very urgent so no problem if this is a temporary problem while you are working on other things.

Best wishes,

Peter

**Comment by martijnbentum** [comment]
Hi Peter,
Is this still an issue?
Best,
Martijn

**Comment by P-J-Brown** [comment]
Hi Martijn,
No it was working again a few days later - must have been a temporary issue perhaps while you were working on something else.
Thanks and best wishes,
Peter
